### ISSUE TITLE
Change aux file names for compatibility with windows

### ISSUE THREAD

**Issue by mosheduminer** [Hirrolot/metalang99#11]
Hi, I was excited to try out your datatype99. Unfortunately metalang99 (which datatype99 requires) uses file names beginning with `aux`, such as `aux.h` and `aux.rst`. Unfortunately, this severely messes with windows, as windows refuses to recognize files named `aux` (they are reserved file names, apparently). As such, it is quite difficult to even delete those files.

I can use easily switch to using WSL, but I would greatly appreciate it if the file names could be changed, and this annoyance resolved (or more like worked around 🙂). 🙏

**Comment by Hirrolot** [comment]
You're welcome!

**Comment by Hirrolot** [comment]
@mosheduminer BTW now it's okay? I renamed `aux.*` -> `util.*` but the Windows CI still fails and I don't know why...

**Comment by mosheduminer** [comment]
I'll test it out in a minute. It's morning where I am 🙂.

**Comment by mosheduminer** [comment]
Hmm, it appears that the `cl` compiler doesn't like your code... I can try to look into it somewhat, but I may not be able to help with that, unfortunately.

**Comment by mosheduminer** [comment]
I figured it out 😄. By default, `cl` passes the `/std:c++14` flag, which doesn't support c99. There isn't a flag for c99, but there are flags for `/std:c11` or `/std:c17` as a flag, and the compilation is successful using either one. See [here](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160#c-standards-support-1).

**Comment by Hirrolot** [comment]
Finally it worked. Thank you very much!
