### ISSUE TITLE
How do you loop over a macro?

### ISSUE THREAD

**Issue by MarcusJohnson91** [Hirrolot/metalang99#18]
That's my problem with this and P99, both are huge convoluted libraries for the preprocessor and every time I try spelunking into these codebases, I just get more confused.

my goal is to use `_Pragma(push_macro(MacroName))` to set MacroName to a list of Test Suites while regstering all the suites

then at the end to loop __COUNTER__ times over MacroName with `_Pragma(pop_macro(MacroName))`

to create a designated initializer of Test Suites that can be written to the executable with linker section magic, and I'm just not sure how to get there.

I've got the linker magic figured out, but I can't figure out how the heck to get the damn looping to work

Can you help?

**Comment by Hirrolot** [comment]
So say when `COUNTER` is 3, your hypothetic loop would result in

```
_Pragma(pop_macro(MacroName))
_Pragma(pop_macro(MacroName))
_Pragma(pop_macro(MacroName))
```

?

**Comment by MarcusJohnson91** [comment]
Exactly.

there's be more to it, stringizing MacroName and concatting it into the proper DI syntax, but that's the gist.

**Comment by MarcusJohnson91** [comment]
So, like.

#define SuiteName Suite1
_Pragma(push_macro("SuiteName"));
#undef SuiteName
#define SuiteName Suite2
_Pragma(push_macro("SuiteName"));

for the setting the name part.

then later on it would be something like:

#undef SuiteName
_Pragma(pop_macro("SuiteName"));
/* SuiteName = Suite2*/
_Pragma(pop_macro("SuiteName"));
/*SuiteName = Suite1*/

**Comment by Hirrolot** [comment]
```c
#include <metalang99.h>

#define POP_MACROS(n)        ML99_EVAL(ML99_repeat(v(n), ML99_reify(v(PRAGMA_POP_MACRO))))
#define PRAGMA_POP_MACRO(_i) _Pragma("pop_macro(\"SuiteName\")")

POP_MACROS(3)
```

Well, this should work. Feel free to modify it to fit your need.

Vanilla preprocessor macros cannot recurse so we need to use custom looping constructs such as `ML99_repeat`.

**Comment by Hirrolot** [comment]
Closed due to inactivity.
