### ISSUE TITLE
Rules engine written (at least partially) in metalang99

### ISSUE THREAD

**Issue by dumblob** [Hirrolot/metalang99#22]
I've recently kind of fell in love with https://github.com/paranim/pararules . But I'm not a Nim user most of the time and would want something like that in pure C.

I wonder whether some form of the `staticRuleset` together with the ["wrapper macro"](https://github.com/paranim/pararules/blob/master/tests/test3.nim ) to add rules to `staticRuleset` in compile time would be viable to write in metalang99.

Would it be worth it? What would be the disadvantage(s)?

Thanks for your thoughts, observations, and recommendations!

**Comment by Hirrolot** [comment]
Well, theoretically, it should be possible to implement with Metalang99, thanks to its iteration facilities. But personally I wouldn't go that far with macro metaprogramming in plain C. If I understand it correctly, these rules return `NimNode`, which is an AST node or something like that. In C, all these rules would therefore then be macros, not ordinary functions. This will inevitably result in inscrutable compiler diagnostics and utterly perplexed readers of the code.

**Comment by dumblob** [comment]
Thanks for the valuable insight.

Basically one would then want to move part of the compile-time computation to runtime thus easing the macro hell. But then the question is whether to not use some more capable preprocessor or rather a transpiler of some sort to accomplish that task. In which case the whole purpose of having this in C would go in vain and it'd be much better just to choose the Nim implementation (which compiles to C).

Closing as answered. Glad you expressed your informed opinion!
