### ISSUE TITLE
Question: Tagged pointer

### ISSUE THREAD

**Issue by ib00** [Hirrolot/metalang99#23]
Is it possible to implement something like this 
https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/util/taggedptr_test.cpp
with metalang99?

I was able to implement tagged pointers by hand, but I am wondering if it can
be generalized using macro processing.

**Comment by Hirrolot** [comment]
Hello! Are you asking specifically about testing the tagged pointer or the [implementation of it](https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/util/taggedptr.h)? Anyway, I guess I know what you need. You can use [`ML99_repeat`](https://metalang99.readthedocs.io/en/latest/gen.html#c.ML99_repeat) to invoke some macro with integers from 0 to N and generate something from within this macro. I hope this helps.
