### ISSUE TITLE
Don't understand how to recurse

### ISSUE THREAD

**Issue by yonghenghuanmie** [Hirrolot/metalang99#24]
I have read the tutorial and write the code according to example but it doesn't work. I took several hours to try different patterns with v() or without v() but still don't figure out how to use it.  So I came here to find some help, here is the code.
```c++
#define _GetUnderlyingType(LayerNumber,CurrentType)															\
	std::enable_if_t<_IsEligibleType<CurrentType,LayerNumber,_default_index>::value,									\
	typename _IsEligibleType<CurrentType,LayerNumber,_default_index>::underlying_type>													

#define _ConstructGetUnderlyingType(TotalLayer,StartLayer,T) ML99_natMatchWithArgs(TotalLayer, v(_ConstructGetUnderlyingType_),StartLayer,T)
#define _ConstructGetUnderlyingType_Z_IMPL(StartLayer,T) v(T)
#define _ConstructGetUnderlyingType_S_IMPL(TotalLayer,StartLayer,T)												\
	_GetUnderlyingType(StartLayer-TotalLayer+2,_ConstructGetUnderlyingType(v(TotalLayer),StartLayer,T))												

	ML99_EVAL(_ConstructGetUnderlyingType(v(1), v(1), v(T)));
```

**Comment by yonghenghuanmie** [comment]
Thank you very much for you answer.
I tried to use ML99_call at the time but it didn't work, now it seems that I forgot to use v() to wrap the metafunction. So all parameters and return values except metafunction name has to be wrapped in v() once? I suggest this should be explained in the tutorial, otherwise it will be confusing to use.

**Comment by Hirrolot** [comment]
You're welcome!

> So all parameters and return values except metafunction name has to be wrapped in v() once?

Not necessarily: you should use `v(...)` whenever you want Metalang99 to copy-paste everything within the parenetheses as-is. However, if you want it to compute some term, `v(expr)` would just stop evaluation of `expr` and paste it as-is.

> I suggest this should be explained in the tutorial, otherwise it will be confusing to use.

Good point! I've just updated the tutorial: https://hirrolot.gitbook.io/metalang99/syntax-and-semantics#appendix-the-use-of-v. Does it look alright now?

**Comment by yonghenghuanmie** [comment]
> Good point! I've just updated the tutorial: https://hirrolot.gitbook.io/metalang99/syntax-and-semantics#appendix-the-use-of-v. Does it look alright now?
Eh, I do see the anchor in the link, but it doesn't jump to it and I don't see the addition.

**Comment by Hirrolot** [comment]
Try this: https://hirrolot.gitbook.io/metalang99/syntax-and-semantics.
The last section is about using `v(...)`.

**Comment by yonghenghuanmie** [comment]
> Try this: https://hirrolot.gitbook.io/metalang99/syntax-and-semantics. The last section is about using `v(...)`. By the way, you may need to reload your page.

Oh, I can see now. Great👍.

**Comment by Hirrolot** [comment]
Closing as resolved. Feel free to ask if you have any additional questions.

**Comment by yonghenghuanmie** [comment]
Hi, I noticed that with more TotalLayer the output is wrong.

	ML99_EVAL(_ConstructGetUnderlyingType(v(2), v(1), v(T)));
	std::enable_if_t<_IsEligibleType<std::enable_if_t<_IsEligibleType<T,1-1+2,_default_index>::value, typename _IsEligibleType<std::enable_if_t<_IsEligibleType<T,1-1+2,_default_index>::underlying_type> ;

As you can see, the number of < is not equal to the number of >.

**Comment by Hirrolot** [comment]
On my computer, it just fails:

```
test.c:17:1: error: macro "_GetUnderlyingType_IMPL" passed 7 arguments, but takes just 2
   17 | ML99_EVAL(_ConstructGetUnderlyingType(v(2), v(1), v(T)));
      | ^~~~~~~~~~~~~~~~~~~~~~~
```

This is because `_GetUnderlyingType` reduces to commas, which are treated as macro arguments. To fix it, you can wrap the call using `ML99_tuple` and then `ML99_UNTUPLE` them:

```c
#define _GetUnderlyingType_IMPL(LayerNumber, CurrentType)                                          \
    v(std::enable_if_t<                                                                            \
        _IsEligibleType<ML99_UNTUPLE(CurrentType), LayerNumber, _default_index>::value,            \
        typename _IsEligibleType<ML99_UNTUPLE(CurrentType), LayerNumber, _default_index>::         \
            underlying_type>)

#define _ConstructGetUnderlyingType(TotalLayer, StartLayer, T)                                     \
    ML99_natMatchWithArgs(TotalLayer, v(_ConstructGetUnderlyingType_), StartLayer, T)
#define _ConstructGetUnderlyingType_Z_IMPL(StartLayer, T) v(T)
#define _ConstructGetUnderlyingType_S_IMPL(TotalLayer, StartLayer, T)                              \
    ML99_call(                                                                                     \
        _GetUnderlyingType,                                                                        \
        v(StartLayer - TotalLayer + 2),                                                            \
        ML99_tuple(_ConstructGetUnderlyingType(v(TotalLayer), v(StartLayer), v(T))))

ML99_EVAL(_ConstructGetUnderlyingType(v(2), v(1), v(T)));
```

The expansion output:

```
std::enable_if_t< _IsEligibleType<std::enable_if_t< _IsEligibleType<T, 1 - 0 + 2, _default_index>::value, typename _IsEligibleType<T, 1 - 0 + 2, _default_index>:: underlying_type>, 1 - 1 + 2, _default_index>::value, typename _IsEligibleType<std::enable_if_t< _IsEligibleType<T, 1 - 0 + 2, _default_index>::value, typename _IsEligibleType<T, 1 - 0 + 2, _default_index>:: underlying_type>, 1 - 1 + 2, _default_index>:: underlying_type>;
```

Hope this helps.

**Comment by yonghenghuanmie** [comment]
Thank you for you help, I still got one more question.
`#define _GetFirst(...)			ML99_listHead(__VA_ARGS__)
#define _GetRest(...)			ML99_variadicsTail(__VA_ARGS__)
#define _GetBeginFrom(n,...)	ML99_listDrop(n,ML99_list(__VA_ARGS__))
#define _GetNthElement(n,...)	_GetFirst(_GetBeginFrom(n,__VA_ARGS__))

#define _GetUnderlyingTypeWithPosition_IMPL(LayerNumber,CurrentType,TypeIndex)																					\
	v(std::enable_if_t<_IsEligibleType<ML99_UNTUPLE(CurrentType),LayerNumber,ML99_UNTUPLE(TypeIndex)>::value,													\
	typename _IsEligibleType<ML99_UNTUPLE(CurrentType),LayerNumber,ML99_UNTUPLE(TypeIndex)>::underlying_type>)

#define _ConstructGetUnderlyingTypeWithPosition(TotalLayer,StartLayer,T,...) ML99_natMatchWithArgs(TotalLayer, v(_ConstructGetUnderlyingTypeWithPosition_),StartLayer,T,##__VA_ARGS__)
#define _ConstructGetUnderlyingTypeWithPosition_Z_IMPL(StartLayer,T,...) v(T)
#define _ConstructGetUnderlyingTypeWithPosition_S_IMPL(TotalLayer,StartLayer,T,...)																			\
	ML99_call(_GetUnderlyingTypeWithPosition,																												\
	v(StartLayer-TotalLayer+2),																																\
	ML99_tuple(_ConstructGetUnderlyingTypeWithPosition(v(TotalLayer),v(StartLayer),v(T),v(__VA_ARGS__))),												\
	_GetNthElement(v(TotalLayer), v(__VA_ARGS__)))

ML99_EVAL(_ConstructGetUnderlyingTypeWithPosition(v(1), v(0x10), v(T),v(1,Byte)));
`
I have problem on the similar pattern.
`
#define _ConstructGetUnderlyingTypeWithPosition(TotalLayer,StartLayer,T,...) ML99_natMatchWithArgs(TotalLayer, v(_ConstructGetUnderlyingTypeWithPosition_),StartLayer,T,ML99_tuple(__VA_ARGS__))
#define _ConstructGetUnderlyingTypeWithPosition_Z_IMPL(StartLayer,T,Tuple) v(T)
#define _ConstructGetUnderlyingTypeWithPosition_S_IMPL(TotalLayer,StartLayer,T,Tuple)																			\
	ML99_call(_GetUnderlyingTypeWithPosition,																													\
	v(StartLayer-TotalLayer+2),																																	\
	ML99_tuple(_ConstructGetUnderlyingTypeWithPosition(v(TotalLayer),v(StartLayer),v(T),ML99_UNTUPLE(Tuple))),													\
	ML99_tuple(_GetNthElement(v(TotalLayer), ML99_UNTUPLE(Tuple))))

`
And I also tried this form, both doesn't work.

**Comment by Hirrolot** [comment]
You call `ML99_UNTUPLE` on the `TypeIndex` parameter in `_GetUnderlyingTypeWithPosition_IMPL`, but you don't `ML99_tuple` it beforehand. In `_ConstructGetUnderlyingTypeWithPosition_S_IMPL`, you need to use `ML99_tuple(_GetNthElement(v(TotalLayer), v(__VA_ARGS__)))` as an argument to `_GetUnderlyingTypeWithPosition`.

Also, you don't need `_GetNthElement`; there's a function in the standard library called `ML99_listGet`:

```c
#define _GetNthElement(n, ...) ML99_listGet(n, ML99_list(__VA_ARGS__))
```

**Comment by yonghenghuanmie** [comment]
Sorry I forgot to restore _GetUnderlyingTypeWithPosition_IMPL, that's actually for the second version. I want to show you I have tried, but both doesn't work.
```c++
#define _GetNthElement(n,...)	ML99_listGet(n, ML99_list(__VA_ARGS__))

#define _GetUnderlyingTypeWithPosition_IMPL(LayerNumber,CurrentType,TypeIndex)								\
	v(std::enable_if_t<_IsEligibleType<ML99_UNTUPLE(CurrentType),LayerNumber,ML99_UNTUPLE(TypeIndex)>::value,		\
	typename _IsEligibleType<ML99_UNTUPLE(CurrentType),LayerNumber,ML99_UNTUPLE(TypeIndex)>::underlying_type>)

#define _ConstructGetUnderlyingTypeWithPosition(TotalLayer,StartLayer,T,...) ML99_natMatchWithArgs(TotalLayer, v(_ConstructGetUnderlyingTypeWithPosition_),StartLayer,T,##__VA_ARGS__)
#define _ConstructGetUnderlyingTypeWithPosition_Z_IMPL(StartLayer,T,...) v(T)
#define _ConstructGetUnderlyingTypeWithPosition_S_IMPL(TotalLayer,StartLayer,T,...)									\
	ML99_call(_GetUnderlyingTypeWithPosition,																\
	v(StartLayer-TotalLayer+2),																			\
	ML99_tuple(_ConstructGetUnderlyingTypeWithPosition(v(TotalLayer),v(StartLayer),v(T),v(__VA_ARGS__))),				\
	ML99_tuple(_GetNthElement(v(TotalLayer), v(__VA_ARGS__))))

ML99_EVAL(_ConstructGetUnderlyingTypeWithPosition(v(1), v(0x10), v(T),v(1,Byte)));
```
Neither this nor removing ML99_UNTUPLE and ML99_tuple of TypeIndex and _GetNthElement will work.

**Comment by Hirrolot** [comment]
Why it doesn't work? What's the expected output? I receive the following expansion:

```
std::enable_if_t< _IsEligibleType<T, 0x10 - 0 + 2, 1>::value, typename _IsEligibleType< T, 0x10 - 0 + 2, 1>::underlying_type>;
```

**Comment by yonghenghuanmie** [comment]
Oh, It's my fault, forget it.😂
Thank you for you patience.

**Comment by yonghenghuanmie** [comment]
Oh, it's my fault, forget it.
Thanks for you patience.

**Comment by Hirrolot** [comment]
We could do the trick with some variadics metaprogramming:

```c
#define _ConstructTemplateParameters_S_IMPL(Total, Current, ...)                                   \
    ML99_TERMS(                                                                                    \
        _GetLongName(v(Current), ML99_variadicsGet(0)(v(__VA_ARGS__))),                            \
        ML99_IF(ML99_VARIADICS_IS_SINGLE(__VA_ARGS__), v(), v(, )),                                \
        _ConstructTemplateParameters(                                                              \
            v(Total),                                                                              \
            ML99_inc(v(Current)),                                                                  \
            ML99_variadicsTail(v(__VA_ARGS__))))
```

This is a fully C99-compliant (C++11) way to accomplish your job.

**Comment by Hirrolot** [comment]
By the way, there's a more neat way to do the same:

```c
#define _PARAM_T typename
#define _PARAM_V auto

#define _ConstructTemplateParameters(...)                                                          \
    ML99_LIST_EVAL_COMMA_SEP(ML99_listMapI(v(_GenTemplateParam), ML99_list(v(__VA_ARGS__))))

#define _GenTemplateParam_IMPL(x, i) v(_PARAM_##x x##i)
#define _GenTemplateParam_ARITY      2

_ConstructTemplateParameters(T, V, T, V)
```

Output:

```
typename T0 , auto V1 , typename T2 , auto V3
```

**Comment by yonghenghuanmie** [comment]
With your patience and help I finally finished my own project, thank you very much.
