### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by brvtalcake** [Hirrolot/metalang99#27]
# Control statements
I was asking myself if implementing custom control statements was a possibility for this project, or if this kind of things completely was up to users to do, on their own.
For example, it could be nice to implement things like "foreach", or along the lines of [those proposed here](https://www.chiark.greenend.org.uk/~sgtatham/mp/).
I was also thinking of things like : 
```c
#define check_in if(((
#define for_only_flags(...) ) | (ML99_LIST_EVAL(ML99_call(ML99_listIntersperse, v(|), ML99_list(v(__VA_ARGS__)))))) == (ML99_LIST_EVAL(ML99_call(ML99_listIntersperse, v(|), ML99_list(v(__VA_ARGS__))))))
#define for_at_least_flags(...) ) & (ML99_LIST_EVAL(ML99_call(ML99_listIntersperse, v(|), ML99_list(v(__VA_ARGS__)))))) == (ML99_LIST_EVAL(ML99_call(ML99_listIntersperse, v(|), ML99_list(v(__VA_ARGS__))))))
```
while working on my own personal project.
It could be used with user-provided flags like : 
```c
#define FLAG1 1U
#define FLAG2 2U
#define FLAG3 4U
// ...
void check_flags_in_var(unsigned int var)
{
    check_in var for_only_flags(FLAG1, FLAG2)
    {
        // do something
    }
    else check_in var for_at_least_flags(FLAG1, FLAG2)
    {
        // ...
    }
// ...
}
```
There would be (of course) the usual ML99_ namespace and with the good style convention.
If you're okay, that would be a pleasure to contribute to this precious repo.

Personally, I think that could fit the purpose of the lib, since there is already a ["Support for C language constructions"](https://metalang99.readthedocs.io/en/latest/gen.html) with gen.h, although it's not as general purpose as the rest of the library (more particularly if we consider the aforementioned header, wich stays quite general purpose).

**Comment by Hirrolot** [comment]
Have you checked [`stmt.h`](https://metalang99.readthedocs.io/en/latest/stmt.html)? This header borrows some of the macros from "Metaprogramming custom control structures in C" you've mentioned.

**Comment by brvtalcake** [comment]
Yeah you're right, I have to admit that I didn't pay that much attention to this particular one. But then my question was (a bit clearlier and shorter) : is there a possibility to include pre-made custom statements ?

**Comment by Hirrolot** [comment]
What are you referring to as "pre-made custom statements"? Aren't those macros in `stmt.h` "pre-maid"?

**Comment by brvtalcake** [comment]
I was thinking about (for example) plain ML99_FOREACH macro (to be directly applied to arrays, without having to contruct it by ourselves) and stuff like that, but I would understand if you didn't want to (since that's actually not that hard to make them). As far as I can see, there's no such thing among the different headers.

**Comment by Hirrolot** [comment]
What semantics is expected for `ML99_FOREACH`? Doesn't `ML99_variadicsForEach` fit your purpose?

**Comment by brvtalcake** [comment]
ML99_variadicsForEach is nice when you know the elements you're going to preprocessed, but for example imagine you have a C-"array" (no real array in C but whatever) and you want to loop on each of its elems (as the non-standard [microsoft C++ foreach](https://learn.microsoft.com/en-us/cpp/dotnet/for-each-in?view=msvc-170) does, for instance), then you don't have such a thing in C. Maybe it's not the best example, but that's the kind of things that could be cool to incorporate. 

The idea is just to "extend" C.
That's pretty much the whole kind of things I am proposing.

**Comment by Hirrolot** [comment]
Ok, now I got you. The "meta" part in Metalang99 means that it's simply a metalanguage, or a macro language, to use more familiar terminology; its idea is to provide a language that can be used to write macros. Metalang99 doesn't attempt to directly extend C -- this is better done by external libraries that can use Metalang99 in their implementation, see my Datatype99 and Interface99.

Feel free to ask any further questions if I'm unclear somewhere.

**Comment by brvtalcake** [comment]
Okay no problem ! I understand perfectly. I'll give a closer look at your other libraries.
