### ISSUE TITLE
Issue with ML99_listFromSeq

### ISSUE THREAD

**Issue by brvtalcake** [Hirrolot/metalang99#28]
When trying to use it on one of the sequences mentioned in the top of `seq.h` doc, I got an error : 

```c
ML99_LIST_EVAL(ML99_listFromSeq(v((+, -, *, /)(123)(~))))
```

```console
error: macro "ML99_cons_IMPL" passed 5 arguments, but takes just 2
```

Maybe this is just me not understanding something ?

**Comment by Hirrolot** [comment]
Apologies for the late response; if you haven't figured it out already, `ML99_cons` accepts only a single argument (without commas) as an item:

```c
#define ML99_cons(x, xs) ML99_call(ML99_cons, x, xs)
```

So if you want to transform the mentioned sequence, ML99 throws an error on the first element -- it contains commas and thus several items.

To workaround the issue, you can wrap the item in parentheses like this:

```c
// (+, -, *, /) 123 ~
ML99_LIST_EVAL(ML99_listFromSeq(v(((+, -, *, /))(123)(~))))
```

I'll reflect this subtlety in the documentation.
