### ISSUE TITLE
List of choices evalued via reified match.

### ISSUE THREAD

**Issue by EngineersBox** [Hirrolot/metalang99#31]
# Context

Hi,

I'm trying to create a system for defining enum entries via a choice of either a label (`<label>`) only or a label and ordinal (`<label> = <ord>`). This is then used in one of two (maybe more later) macros that expand to either the full enum entry definitions or to the stringified labels.

## Example
```c
// Converts to entries
#define ENUM_ENTRIES(...) { ... }
// Converts to stringified names
#define ENUM_ENTRY_NAMES(...) { ... }

#define testEnumEntries \
	ENUM_ENTRY(entry_a), \
	ENUM_ENTRY_ORD(entry_b, 2)

typedef enum {
	ENUM_ENTRIES(testEnumEntries)
} test_enum;

const char* test_enum_names[2] = {
	ENUM_ENTRY_NAMES(testEnumEntries)
};
```

Resulting in

```c
typedef enum {
	entry_a,
	entry_b = 2
} test_enum;

const char* test_enum_names[2] = {
	"entry_a",
	"entry_b"
};
```

# Implementation

To implement this, I have gone with macros for defining enum entries that create choice variants and then an evaluation via matching that is applied over a given list of entries:

```c
#define ENUM_ENTRY(name) ML99_choice(v(ENUM_ENTRY), v(name))
#define EUNM_ENTRY_ORD(name, id) ML99_choice(v(EUNM_ENTRY_ORD), v(name), v(id))

#define createEnumEntry_ENUM_ENTRY_IMPL(name) v(name)
#define createEnumEntry_EUNM_ENTRY_ORD_IMPL(name, id) v(name = id)
#define createEnumEntry(entry) ML99_match(entry, v(createEnumEntry_))
#define enumEntryExtractName(choice) ML99_stringify(ML99_tupleGet(0)(ML99_tuple(ML99_choiceData(choice))))

#define ENUM_ENTRIES(...) ML99_LIST_EVAL_COMMA_SEP( \
    ML99_listMap( \
        ML99_reify(v(createEnumEntry)), \
        ML99_list(__VA_ARGS__) \
    ) \
)
#define ENUM_ENTRY_NAMES(...) ML99_LIST_EVAL_COMMA_SEP( \
    ML99_listMap( \
        ML99_reify(v(enumEntryExtractName)), \
        ML99_list(__VA_ARGS__) \
    ) \
)

#define testEnumEntries \
    ENUM_ENTRY(entryA), \
    EUNM_ENTRY_ORD(entryB, 3)

typedef enum {
    ENUM_ENTRIES(testEnumEntries)
} test_enum;

const char* test_enum_names[2] = {
    ENUM_ENTRY_NAMES(testEnumEntries)
};
```

## Output

However, this does not yield the expected result, rather the following

```c
typedef enum {
	(0args,
	    ML99_match, (ENUM_ENTRY,
	    entryA), (0v,
	    createEnumEntry_)) , (0args,
	    ML99_match, (EUNM_ENTRY_ORD,
	    entryB, 3), (0v,
	    createEnumEntry_))
} test_enum;

const char* test_enum_names[2] = {
    (0args, ML99_stringify, (0args, ML99_PRIV_tupleGet_0, (
                                 0args, ML99_tuple, (0args, ML99_choiceData, (ENUM_ENTRY, entryA))))),
    (0args, ML99_stringify, (0args, ML99_PRIV_tupleGet_0, (
                                 0args, ML99_tuple, (0args, ML99_choiceData, (EUNM_ENTRY_ORD, entryB, 3)))))
};
```

## Notes

Im using GCC 12.3.0, specifically mipsel-none-elf-gcc for targeting an R3000 MIPS-2 arch (so a bit of a weird setup, but shouldn't change anything in the preprocessor eval AFAICT).

From what I understand (from my limited knowledge of Metalang99), the result of each element being passed through the reified `createEnumEntry` macro has not actually been evaluated when `ML99_LIST_EVAL_COMMA_SEP` was applied, rather the list was assembled from the results but the evaluation context did not pass down into the list elements (Referencing #26 since it has to have, on the surface, the same result). I would assume this means that at some level of the `createEnumEntry` variants I need to do some evaluation that is then passed as a literal. Though I'm ensure as to whether that is actually the case or I've misunderstood the utilisation of choices through lists and the application of reified macros via (what I assume under the hood is) `ML99_appl(...)`.

Could I get a hand with understanding what I'm missing here?

**Comment by Hirrolot** [comment]
What you get is the internal representation of a Metalang99 terms. To evaluate it, you can use `ML99_EVAL`:

```c
typedef enum {
    ML99_EVAL(ENUM_ENTRIES(testEnumEntries))
} test_enum;

const char* test_enum_names[2] = {
    ML99_EVAL(ENUM_ENTRY_NAMES(testEnumEntries))
};
```

**Comment by EngineersBox** [comment]
Thanks for the fast reply! Indeed, I thought that might have been the case, so I tried with direct evaluation before, without the desired result:

```c
ML99_PRIV_REC_NEXT_ML99_PRIV_EVAL_ENUM_ENTRY(ML99_PRIV_EVAL_0callUneval_K, (ML99_PRIV_REC_STOP, (~), 0fspace, (, ),
 ((0args,
    ML99_match, (EUNM_ENTRY_ORD,
    entryB, 3), (0v,
    createEnumEntry_)), (0end, ~), ~),
    ML99_match), 0fcomma, (), ((0v,
    createEnumEntry_), (0end, ~), ~),
    entryA)(1)()
```

This seems peculiar to me, almost like the form was evaluated correctly but then re-parsed into ML99 terms before being output to the source file?

**Comment by Hirrolot** [comment]
Apologies for the confusion, now I see that your code already uses `ML99_LIST_EVAL_COMMA_SEP`.

The real problem is that `ML99_reify` expects an "ordinary" functional macro (whose expansion is just wrapped in `v(...)`), while your `createEnumEntry` and `enumEntryExtractName` macros expand to Metalang99 terms. To fix it, you can rewrite the code as follows:

```c
#define ENUM_ENTRY(name) ML99_choice(v(ENUM_ENTRY), v(name))
#define EUNM_ENTRY_ORD(name, id) ML99_choice(v(ENUM_ENTRY_ORD), v(name), v(id))

#define createEnumEntry_ENUM_ENTRY_IMPL(name) v(name)
#define createEnumEntry_ENUM_ENTRY_ORD_IMPL(name, id) v(name = id)

#define createEnumEntry_IMPL(entry) ML99_match(v(entry), v(createEnumEntry_))
#define createEnumEntry_ARITY 1

#define enumEntryExtractName_IMPL(choice) ML99_stringify(ML99_tupleGet(0)(ML99_tuple(ML99_choiceData(v(choice)))))
#define enumEntryExtractName_ARITY 1

#define ENUM_ENTRIES(...) ML99_LIST_EVAL_COMMA_SEP( \
    ML99_listMap( \
        v(createEnumEntry), \
        ML99_list(__VA_ARGS__) \
    ) \
)
#define ENUM_ENTRY_NAMES(...) ML99_LIST_EVAL_COMMA_SEP( \
    ML99_listMap( \
        v(enumEntryExtractName), \
        ML99_list(__VA_ARGS__) \
    ) \
)
```

(I've also fixed a number of typos such as `EUNM`.)

The expansion will be:

```c
typedef enum {
    entryA , entryB = 3
} test_enum;
const char* test_enum_names[2] = {
    "entryA" , "entryB"
};
```

**Comment by EngineersBox** [comment]
Ahh ok that makes more sense to me now, thanks for taking the time to explain that and debug. Much appreciated 🙇🏼
